image: gitpod/workspace-postgresql

tasks:
  - name: sveltekit
    init: pnpm i
    command: pnpm dev
  - name: prisma
    init: npx prisma db push
  - name: .env
    init: echo "SECRET=asd" > .env; exit

ports:
  - port: 5173
    visibility: private
    onOpen: open-browser
  - port: 5432
