image: gitpod/workspace-postgresql

tasks:
  - name: sveltekit
    init: pnpm i
    command: pnpm dev
  - name: prisma
    init: npx prisma db pull

ports:
  - port: 5173
    visibility: private
    onOpen: open-browser
